name: Deploy

env:
  AWS_REGION: us-east-2
  APP_ENV: prod
  NUXT_PUBLIC_MIXIN_CLIENT_ID: 16b00c6d-cdf2-41c9-ad22-7539e1ea9ef0
  NUXT_PUBLIC_MIXIN_API_BASE_URL: "https://api.mixin.one"
  NUXT_PUBLIC_TALKEE_CLIENT_ID: 61504be8-a9da-477d-9e18-448ac3780919
  NUXT_PUBLIC_TALKEE_API_BASE_URL: "https://talkee-api.pando.im/api"
  NUXT_PUBLIC_BOTASTIC_CLIENT_ID: 0224cb95-87eb-4794-86d2-06f19350d9d7
  NUXT_PUBLIC_BOTASTIC_API_BASE_URL: "https://botastic-api.pando.im/api"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'pandodao'
    steps:
      # prepare
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      # build developer docs
      - run: yarn install --frozen-lockfile

      - name: Build Docs
        run: yarn docs:build

      # build console
      - name: Prepare to build console
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        working-directory: ./console
        run: yarn --frozen-lockfile --non-interactive

      - name: Build console
        working-directory: ./console
        run: APP_ENV=${{ env.APP_ENV }} yarn generate

      - name: Move console/.output/public to docs/.vitepress/dist
        run: cp -a console/.output/public docs/.vitepress/dist/console

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: docs/.vitepress/dist
      #     cname: developers.pando.im

      # upload to aws
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_ACCESS_KEY_SECRET }}
      - run: aws s3 cp --recursive docs/.vitepress/dist ${{ secrets.S3_URL_PROD }} --acl public-read
      - run: aws s3 cp --recursive docs/.vitepress/dist ${{ secrets.S3_URL_PROD }} --exclude "*" --include "*.html" --cache-control "no-cache" --acl public-read
